name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Menjalankan setiap hari pada jam 00:00 UTC
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-contribution-grid-snake.svg
          theme: default # Gunakan warna default GitHub
          pixel_size: 10 # Membuat kotak lebih kecil

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Snake Animation"
          branch: output
